try:
    prin('a')
except Exception as e:
    print(e)
